### ISSUE TITLE
Use scroll-margin-top

### ISSUE THREAD

**Issue by ewels** [nf-core/website#628]
Because of our floating nav bar, headers are hidden when linked to with a `#something` softlinks. To get around this we use an old CSS hack where we have a large padding on all headers with a negative margin to remove the whitespace.

Instead of this, it would be nicer to use the relatively new `scroll-margin-top` CSS attribute. @alneberg told me about this as he found it in [this PR](https://github.com/SciLifeLab/genomics-status/pull/554/files#diff-bafb36ee016c6b4b1697cf209707204593a5409d5a6fcebee5e3f5b69a5f089eR5-R8):

```css
/* Internal links should not be hidden behind top banner */
h1, h2, h3, h4, h5, h6, .link-target-offset {
  scroll-margin-top: 60px;
}
```

There may be some incompatibilities with Safari but I think that we can get around that by _also_ using the non-standard `scroll-snap-margin-top` attribute as well: https://caniuse.com/mdn-css_properties_scroll-margin-top
